rpi-common: Remove no longer required sdk/ndk versions
sdk/ndk versions are not required anymore from Android 15+.
Let's remove to avoid below build (full) issue:

ERROR: files are incompatible: Framework manifest and device
compatibility matrix are incompatible: Vndk version 34 is not
supported. Supported versions in framework manifest are: []:
Success

Signed-off-by: Kha Tran <khab1304690@gmail.com>